[project]
name = "projectscrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "scrapy>=2.12.0",
    "sqlalchemy>=2.0.36",
]
